# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO

spring:
  application:
    name: KuFlow Engine Worker Sample Loan
  config:
    import:
      - "classpath:config/application-fillme.yml"
      - "optional:classpath:config/application-local.yml"
  main:
    web-application-type: none

kuflow:
  activity:
    kuflow:

      # NOTE that the endpoint is the KUFLOW LIVE environment for
      # the KUFLOW REST API.
      endpoint: https://api.kuflow.com/v1

application:
  temporal:

    # NOTE that the endpoint is the KUFLOW LIVE environment for
    # the KUFLOW GRPC TEMPORAL API.
    target: engine.kuflow.com:443
